### PR TITLE
Update code and added const

### PR DESCRIPTION
**Pull request by khimji9883**
removed unused import's

### CODE REVIEW

**Comment by ShivamMenda** [comment]
@khimji9883 As much as we appreciate code quality changes please do make PR's in accordance with the issues available only. Please select an issue get yourself assigned and then make a PR only pertaining to that issue.

**Comment by khimji9883** [comment]
#10 
@ShivamMenda Please check Im not able to self assign.

**Comment by ShivamMenda** [comment]
@khimji9883 I've assigned you the issue I'll review the PR and get back to you.

**Comment by ManjunathRK1251** [comment]
Hey @khimji9883, we do appreciate the code quality changes and code refactoring but see if you can contribute to the other issues that are listed in the issues tab then it'd be a valuable contribution! 
There are certain guidelines that must be followed before accepting a PR for the hacktoberfest , our team is having a discussion regarding this issue and we'll get back to you soon!

Till then Happy Opensourcing :)

**Comment by khimji9883** [comment]
@ManjunathRK1251 
I will try to solve the rest of your issue

But please do not give spam and invalid tag to this PR!
You merge it after the month of October (after the Hacktoberfest is over)! So that the rules and guidelines of Hacktoberfest don't break!

**Pull request closed without merging**
